CREATE TABLE client (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(200) NOT NULL,
                        CONSTRAINT client_name_length CHECK (LENGTH(name) BETWEEN 3 AND 200)
);

CREATE TABLE planet (
                        id VARCHAR(50) PRIMARY KEY,
                        name VARCHAR(500) NOT NULL,
                        CONSTRAINT planet_id_format CHECK (REGEXP_LIKE(id, '^[A-Z0-9]+$')),
                        CONSTRAINT planet_name_length CHECK (LENGTH(name) BETWEEN 1 AND 500)
);

CREATE TABLE ticket (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        created_at TIMESTAMP NOT NULL,
                        client_id BIGINT NOT NULL,
                        from_planet_id VARCHAR(50) NOT NULL,
                        to_planet_id VARCHAR(50) NOT NULL,

                        CONSTRAINT fk_ticket_client
                            FOREIGN KEY (client_id)
                                REFERENCES client(id)
                                ON DELETE CASCADE,

                        CONSTRAINT fk_ticket_from_planet
                            FOREIGN KEY (from_planet_id)
                                REFERENCES planet(id),

                        CONSTRAINT fk_ticket_to_planet
                            FOREIGN KEY (to_planet_id)
                                REFERENCES planet(id),

                        CONSTRAINT ticket_planets_different
                            CHECK (from_planet_id <> to_planet_id)
);